# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/albemute/Документы/GitHub/Project/color.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(308, 164)
        Dialog.setStyleSheet("background-image: url(:/newPrefix/Mirai Nikki.jpeg);")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setMaximumSize(QtCore.QSize(1000, 1000))
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("background-image: url(:/newPrefix/Mirai Nikki.jpeg);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_9 = QtWidgets.QFrame(self.frame)
        self.frame_9.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_9.setMaximumSize(QtCore.QSize(1000, 1000))
        self.frame_9.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.frame_9.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 0, 0);\n"
"     border: 1px solid rgba(255,255,255,40);\n"
"     border-radius:10px;\n"
"width: 15;\n"
"height: 15;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:rgba(255,255,255,70);\n"
"}")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_21 = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_21.setMinimumSize(QtCore.QSize(40, 30))
        self.pushButton_21.setMaximumSize(QtCore.QSize(40, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setItalic(True)
        self.pushButton_21.setFont(font)
        self.pushButton_21.setStyleSheet("image:url(:/newPrefix/7036.970.png)")
        self.pushButton_21.setText("")
        self.pushButton_21.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_21.setObjectName("pushButton_21")
        self.gridLayout.addWidget(self.pushButton_21, 4, 4, 1, 1)
        self.pushButton_20 = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_20.setMinimumSize(QtCore.QSize(40, 30))
        self.pushButton_20.setMaximumSize(QtCore.QSize(40, 30))
        self.pushButton_20.setStyleSheet("image:url(:/newPrefix/orange.png)")
        self.pushButton_20.setText("")
        self.pushButton_20.setObjectName("pushButton_20")
        self.gridLayout.addWidget(self.pushButton_20, 4, 3, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_11.setMinimumSize(QtCore.QSize(40, 30))
        self.pushButton_11.setMaximumSize(QtCore.QSize(40, 30))
        self.pushButton_11.setStyleSheet("\n"
"image: url(:/newPrefix/green-circle-svgrepo-com.svg);")
        self.pushButton_11.setText("")
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout.addWidget(self.pushButton_11, 0, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_10.setMinimumSize(QtCore.QSize(40, 30))
        self.pushButton_10.setMaximumSize(QtCore.QSize(40, 30))
        self.pushButton_10.setStyleSheet("\n"
"image: url(:/newPrefix/red-circle-svgrepo-com.svg);\n"
"")
        self.pushButton_10.setText("")
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout.addWidget(self.pushButton_10, 0, 4, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_12.setMinimumSize(QtCore.QSize(40, 30))
        self.pushButton_12.setMaximumSize(QtCore.QSize(40, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setItalic(True)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setStyleSheet("image: url(:/newPrefix/purple-circle-svgrepo-com.svg);")
        self.pushButton_12.setText("")
        self.pushButton_12.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout.addWidget(self.pushButton_12, 0, 1, 1, 1)
        self.pushButton_18 = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_18.setMinimumSize(QtCore.QSize(40, 30))
        self.pushButton_18.setMaximumSize(QtCore.QSize(40, 30))
        self.pushButton_18.setStyleSheet("image: url(:/newPrefix/322557044025211.png)")
        self.pushButton_18.setText("")
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout.addWidget(self.pushButton_18, 4, 0, 1, 1)
        self.pushButton_19 = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_19.setMinimumSize(QtCore.QSize(40, 30))
        self.pushButton_19.setMaximumSize(QtCore.QSize(40, 30))
        self.pushButton_19.setStyleSheet("image: url(:/newPrefix/circle_PNG4.png)")
        self.pushButton_19.setText("")
        self.pushButton_19.setObjectName("pushButton_19")
        self.gridLayout.addWidget(self.pushButton_19, 4, 1, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_13.setMinimumSize(QtCore.QSize(40, 30))
        self.pushButton_13.setMaximumSize(QtCore.QSize(40, 30))
        self.pushButton_13.setStyleSheet("image: url(:/newPrefix/blue-circle-svgrepo-com.svg)")
        self.pushButton_13.setText("")
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout.addWidget(self.pushButton_13, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.frame_9)
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
import res_rc
